export const  positions = [
    'REGIONAL DIRECTOR',
    'ASSISTANT REGIONAL DIRECTOR FOR ADMINISTRATION',
    'ASSISTANT REGIONAL DIRECTOR FOR OPERATIONS/CON C, LOGISTICS DIVISION',
    'REGIONAL CHIEF DIRECTORIAL STAFF',
    'CHIEF LEGAL SERVICES UNIT/ CON ACTING C, ADMIN DIVISION',
    'ACTING C, FINANCIAL DISBURSEMENT SECTION, FMD ',
    'ACTING C, OPERATIONS DIV ',
    'ACTING C, FSED DIV',
    'ACTING C, PLANS AND PROGRAM DIV CON C,DENTAL SERVICE UNIT RHSS',
    'C, SRU',
    'C, HEALTH SERVICE UNIT CON HSU, BFP 9',
    'C, HEALTH SERVICE UNIT BFP10',
    'C,FINANCE MANAGEMENT DIVISION',
    'ACTING C, HUMAN RESOURCE MANAGEMENT SECTION, ADMIN DIV',
    'C, NURSE, HEALTH SERVICE',
    'ACTING C, BUDGET SECTION',
    'OIC, ACCOUNTING SECTION',
    'REGIONAL SAPD',
    'REGIONAL PUBLIC INFORMATION UNIT',
    'R10 C, FCOS'
]



export const userType = [
    'REGIONAL DIRECTOR',
    'DISTRICT DIRECTOR',
    'FIRE DIRECTOR',
    'ADMIN',
]